# Generated by Django 3.0.3 on 2020-03-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20200301_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Служба',
                'verbose_name_plural': 'Службы',
            },
        ),
    ]
