# Generated by Django 3.0.4 on 2020-03-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_manufacturing_productionarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='production_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='production_area', to='machines.ProductionArea'),
            preserve_default=False,
        ),
    ]
