# Generated by Django 3.0.3 on 2020-03-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_developer'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Ремонт', 'verbose_name_plural': 'Ремонты'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Действие с ремонтом', 'verbose_name_plural': 'Действия с ремонтами'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='service',
        ),
        migrations.AddField(
            model_name='event',
            name='services',
            field=models.ManyToManyField(to='machines.Developer'),
        ),
    ]
