# Generated by Django 3.0.3 on 2020-03-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_developer'),
        ('events', '0002_auto_20200302_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='services',
            field=models.ManyToManyField(related_name='developers', to='machines.Developer'),
        ),
    ]
